name: CD

on:
    push:
     branches:
       - master
    
jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: maven
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: release-please
    steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Set up JDK 11
          uses: actions/setup-java@v4
          with:
            java-version: '11'
            distribution: 'temurin'
            cache: 'maven'
            server-id: github
        
        - name: Build with Maven
          run: |
           mvn -B -P github package -file pom.xml
         
        - name: Publish to GitHub Packages Apache Maven
          # if: ${{needs.release-please.outputs.release_created}}
          run: mvn --batch-mode deploy
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
        # - name: upload artifact
        #   uses: actions/upload-artifact@v4
        #   with:
        #    name: Package
        #    path: staging
       
